### PR TITLE
v0.5.22: add new --threads option & XSOS_PS_THREADS env var for #146

### PR DESCRIPTION
**Pull request by ryran**
Adds new `--threads` option for use with the ps module (`xsos --ps` or `xsos -p` or `xsos --P`).

When used on sosreport, it will parse `SOSROOT/sos_commands/process/ps_auxwwwm` instead of the default `SOSROOT/ps` (which links to `SOSROOT/sos_commands/process/ps_auxwww`).

On localhost, it will actually execute `ps auxm` instead of `ps aux`. See #146 for example output.

### CODE REVIEW

**Comment by lathan** [comment]
Thanks @ryran !

I can't comment on the code itself.
The functionality looks great, it also works with `xsos -ay --threads` which is what I will be using.
I do have one comment on functionality, maybe in the default `-ps` output, we can have a line that just gives a total number of D and Z processes which includes threads, and make it scary-red or scary-orange. This way the default output exposes a potential problem without changing the current behaviour.
Finally, if you can split the whitespace changes into their own commit, future @ryran might thank you. :P

**Comment by ryran** [comment]
Great idea.

```
$ x -v0 -p
PS CHECK
  Total number of threads/processes: 
    4800/998
  Top users of CPU & MEM: 
    USER     %CPU   %MEM  RSS 
    root     11.3%  0.2%  1.19 GiB
    boomadm  9.8%   0.7%  1.93 GiB
  Uninteruptible sleep threads/processes (92/0): 
    USER      PID    %CPU  %MEM  VSZ-MiB  RSS-MiB  TTY    STAT  START  TIME     COMMAND  
    [None] 
    Blocked threads detected; run with --threads option for full detail
  Defunct zombie threads/processes (0/0): 
    USER      PID    %CPU  %MEM  VSZ-MiB  RSS-MiB  TTY    STAT  START  TIME     COMMAND  
    [None] 
  Top CPU-using processes: 
    USER      PID    %CPU  %MEM  VSZ-MiB  RSS-MiB  TTY    STAT  START  TIME     COMMAND  
    root      25889  5.0   0.0   108      1        pts/8  R+    10:10  0:00     /bin/ps 
    root      2956   2.7   0.1   454      70       ?      SLsl  2014   7606:29  corosync 
    boomadm   61562  2.0   0.0   1337     54       ?      S<l   May22  789:37   /opt/boom/lib/dzl_jqmd 
    boomadm   60910  1.7   0.6   8666     449      ?      S<l   May22  670:21   /opt/boom/share/mysql/5.0.24/bin/mysqld 
    root      1533   1.6   0.0   35       10       ?      S<s   Jun15  74:47    /opt/perf/bin/scopeux 
  Top MEM-using processes: 
    USER      PID    %CPU  %MEM  VSZ-MiB  RSS-MiB  TTY    STAT  START  TIME     COMMAND  
    boomadm   60910  1.7   0.6   8666     449      ?      S<l   May22  670:21   /opt/boom/share/mysql/5.0.24/bin/mysqld 
    root      19215  0.6   0.1   409      115      pts/8  S+    09:55  0:05     /usr/bin/python 
    root      2956   2.7   0.1   454      70       ?      SLsl  2014   7606:29  corosync 
    boomadm   62370  0.1   0.1   2878     66       ?      S<l   May22  48:38    /opt/boom/lib/dzl_dlmd 
    boomadm   64468  0.2   0.0   3287     64       ?      S<l   May22  90:19    /opt/boom/lib/dzl_dsmd 
```

The `Blocked threads detected; run with --threads option for full detail` warning is printed with the `Warn1` color (yellow/orange by default).

As for the whitespace changes: yeah, it was pretty dumb to mix it in with these commits, but oh well. :)

**Comment by lathan** [comment]
Looks perfect.

**Comment by lathan** [comment]
Also, check out #150

**Comment by ryran** [comment]
Blech. Ran into some weird conflicts. Just going to start with a fresh branch.

**Pull request closed without merging**
