### PR TITLE
lsblk added

### PR DESCRIPTION
**Pull request by joe-speedboat**
Hi Ryan
I found your project in RHN, great work, thanks.
I added lsblk, please look into the code, if it is ok, just add it.
I have more Ideas if you like to enrich, let me know ... to create my own fork would be the last option I would like to choose!
thanks Chris

### CODE REVIEW

**Comment by ptalbert** [comment]
Hi Joe,

This looks nice; thank you for providing it.

I see it hardcodes the sosreport df file as sos_commands/filesys/df_-al_-x_autofs . But I have an sosreport here where the path is sos_commands/filesys/df_-al .

So maybe that could be a bit smarter?

Patrick

**Comment by joe-speedboat** [comment]
> Hi Joe,
> 
> This looks nice; thank you for providing it.
> 
> I see it hardcodes the sosreport df file as sos_commands/filesys/df_-al_-x_autofs . But I have an sosreport here where the path is sos_commands/filesys/df_-al .
> 
> So maybe that could be a bit smarter?
> 
> Patrick
Hi @ptalbert 
Hmm, I could not find you cmd:
```
[root@ansible xsos]# ls -l /root/sosreport-ansible-2019-05-31-uncslpr/sos_commands/filesys/
total 24
-rw-r--r--. 1 root root 1996 May 31 15:57 df_-ali_-x_autofs
-rw-r--r--. 1 root root 2027 May 31 15:57 df_-al_-x_autofs
-rw-r--r--. 1 root root 3180 May 31 15:57 findmnt
-rw-r--r--. 1 root root  492 May 31 15:57 lslocks
-rw-r--r--. 1 root root   60 May 31 15:57 ls_-ltradZ_.tmp
-rw-r--r--. 1 root root 2523 May 31 15:57 mount_-l
[root@ansible xsos]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@ansible xsos]# rpm -q sos
sos-3.6-17.el7.centos.noarch
```
Would you mind if I commit few more cmds that are visible in sosreport?
Just enough to get our 1st and 2nd level support using it on a daily base? would be great!
Thanks
Chris

**Comment by superjamie** [comment]
The idea here is that different versions of sos provide the same output (eg: `df -al`) in slightly different locations, so we have to check for each one. I'm already doing this exact thing elsewhere, see the variable `dfalfile` in commit 0ff7b290. You can use that variable if it's within scope of your patch, or reuse the same code.

You are very welcome to add more useful output to xsos. It would be better to keep each change or addition to a separate PR, as opposed to adding many things on the same PR.

**Comment by superjamie** [comment]
Hi Chris,

I used part of your commits and finished this feature off, it's now merged.

You are credited as the contributor in the commit message.

Closing this PR.

**Pull request closed without merging**
